return {
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-758532836"]={
    configuration_options={
      AUTOPAUSECONSOLE=true,
      AUTOPAUSEMAP=true,
      AUTOPAUSESINGLEPLAYERONLY=true,
      ENABLECLIENTPAUSE=true,
      ENABLEHOTKEY=true,
      KEYBOARDTOGGLEKEY="P" 
    },
    enabled=true 
  } 
}