return {
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-758532836"]={
    configuration_options={
      AUTOPAUSECONSOLE=true,
      AUTOPAUSEMAP=true,
      AUTOPAUSESINGLEPLAYERONLY=true,
      ENABLECLIENTPAUSE=true,
      ENABLEHOTKEY=true,
      KEYBOARDTOGGLEKEY="P" 
    },
    enabled=true 
  } 
}